version: "3.8"
services:
  zania:
    build: .
    container_name: zania
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  tests:
    build: .
    command: pytest -v -s
    depends_on:
      - zania