from pydantic import BaseModel, Field
from typing import List, Dict

# class Product(BaseModel):
#     # product_id: int = Field(..., example=1) #generated by system
#     name: str = Field(..., example="product1")
#     description: str = Field(..., example="description1")
#     price: float = Field(..., example=999.99)
#     stock: int = Field(..., example=10)
class Product(BaseModel):
    # id: str = Field(..., json_schema_extra={"example": "PRODUCT-ABCDEFGH"})
    name: str = Field(..., json_schema_extra={"example": "product1"})
    description: str = Field(..., json_schema_extra={"example": "description1"})
    price: float = Field(..., json_schema_extra={"example": 999.99})
    stock: int = Field(..., json_schema_extra={"example": 10})


class ProductResponse(BaseModel):
    product_id: int
    name: str
    description: str
    price: float
    stock: int